name: Building rust project on different architectures

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-aarch64-gnu
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
          #- os-name: Linux-aarch64-musl
          #  runs-on: ubuntu-24.04
          #  target: aarch64-unknown-linux-musl
          - os-name: Linux-riscv64-gnu
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu
          #- os-name: Linux-riscv64-musl
          #  runs-on: ubuntu-24.04
          #  target: riscv64gc-unknown-linux-musl

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1.0.4
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

